# Generated by Django 5.2.9 on 2026-01-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicrm', '0022_refresh_getprospect_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='exclude_follow_up_siblings',
            field=models.BooleanField(default=True, help_text='When true and this communication follows up on another, omit contacts already targeted by other follow-ups of the same parent.', verbose_name='Exclude contacts already in sibling follow-ups'),
        ),
    ]
