# Generated by Django 5.2.9 on 2025-12-27 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0024_email_from_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('channel', 'imap_uid'), name='unicom_message_channel_imap_uid_unique'),
        ),
    ]
