# Generated by Django 5.2.9 on 2025-12-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0025_message_unicom_message_channel_imap_uid_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email_sender_authenticated',
            field=models.BooleanField(default=True, help_text='Email-only: True when sender identity passed SPF/DKIM/DMARC (always True for other platforms).'),
        ),
    ]
