# Generated by Django 5.2.16 on 2026-08-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0026_message_email_sender_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='failure_kind',
            field=models.CharField(blank=True, help_text='Machine-readable classification of the most recent failure', max_length=32),
        ),
        migrations.AddField(
            model_name='request',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='last_retried_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Earliest time a worker may atomically retry a transient failure', null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of automatic retries already claimed for this request'),
        ),
        migrations.AddField(
            model_name='request',
            name='retry_exhausted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
