# Generated by Django 5.2.17 on 2026-08-20 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicom', '0027_request_failure_kind_request_last_attempt_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailBackfillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('total_messages', models.PositiveIntegerField(default=0)),
                ('processed_messages', models.PositiveIntegerField(default=0)),
                ('imported_messages', models.PositiveIntegerField(default=0)),
                ('skipped_messages', models.PositiveIntegerField(default=0)),
                ('failed_messages', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_backfill_jobs', to='unicom.channel')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
