# Generated by Django 5.2.17 on 2026-10-03 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_preserve_legacy_request_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.CharField(db_index=True, max_length=255)),
                ('request_id', models.UUIDField(db_index=True, null=True)),
                ('model', models.CharField(max_length=255)),
                ('response_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('incomplete', 'Incomplete')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('input_tokens', models.PositiveIntegerField(null=True)),
                ('cached_input_tokens', models.PositiveIntegerField(null=True)),
                ('output_tokens', models.PositiveIntegerField(null=True)),
                ('reasoning_tokens', models.PositiveIntegerField(null=True)),
                ('usage', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
